language: php
php:
- 7.0
- 7.1
- 7.2
install:
- composer install
script:
- ./vendor/bin/phpunit --bootstrap test/phpunit/bootstrap.php test/phpunit/
notifications:
  on_success: never
  on_failure: always
